#!/bin/bash

RUTA_LOG_SCAN_FILE=/root/apps/codes/log-scan

echo "El script ejecutará un análisis al sistema detectando infecciones por CryptoPHP"
echo "harás el escaneo a un solo usuario o a todos?"
echo "1-. Un único usuario"
echo "2-. Todos"
echo "Opción (1,2): "
read OPCION

case $OPCION in
	1 )
		echo "Ingrese el username: "
		read USER
		FILE_LOG=$(date +%d-%m-%Y)_$USER
		echo "El escaneo iniciará en 5 segundos..."
		sleep 5
		echo "Iniciando análisis CryptoPHP..."
		./check_filesystem.py /home/$USER/public_html | grep '.png' >> $USER-$(date +%d%m%Y)-crypto.log
		exit 1
		;;
	2 ) 
		FILE_LOG=$(date +%d-%m-%Y)_resultado
		echo "El resultado del escaneo se guardará en $RUTA_LOG_SCAN_FILE/$FILE_LOG"
		echo "El escaneo iniciará en 5 segundos..."
		for USER in `cat /etc/trueuserdomains | awk '{print $2}'`
		do
        	if [ "$USER" != "patovs" ]
        	then
				echo "Iniciando análisis CryptoPHP..."
				./check_filesystem.py /home/$USER/public_html | grep '.png' >> $USER-$(date +%d%m%Y)-crypto.log
        	fi
		done
		echo "Escaneo terminado."
		exit 1
		;;
	3 )
		echo "Ingrese el username: "
		read USER
		FILE_LOG=$(date +%d-%m-%Y)_$USER
		echo "El escaneo iniciará en 5 segundos..."
		sleep 5
		echo "Iniciando análisis CryptoPHP..."
		./check_filesystem.py /home/$USER/public_html | grep '.png' >> $USER-$(date +%d%m%Y)-crypto.log
		exit 1
		;;
esac


