#!/bin/bash
OPCION=$1
RUTA_LOG_SCAN_FILE=/root/apps/codes/log-scan

echo "El script ejecutará un análisis al sistema detectando infecciones PHP y otras truculencias"
echo "harás el escaneo a un solo usuario o a todos?"
echo "1-. Un único usuario"
echo "2-. Todos"
echo "Opción (1,2): "
#read OPCION

case $OPCION in
	1 )
		echo "Ingrese el username: "
		read USER
		FILE_LOG=$(date +%d-%m-%Y)_$USER
		echo "El resultado será guardado en el archivo $RUTA_LOG_SCAN_FILE/$FILE_LOG"
		echo "El escaneo iniciará en 5 segundos..."
		sleep 5
		egrep -n -r -I --exclude="sym" '(\\x[a-z]|\\x[0-9]|<?php if\(isset\(|eval\(base64_decode\(gzuncompress|gzuncompress|base64_decode|;eval\()|GIF89aG|b374k' /home/$USER/public_html --include=*.php | awk -F":" '{print $1":"$2":\t"$3}' | egrep '(:1:)' >> $RUTA_LOG_SCAN_FILE/$FILE_LOG
		echo "Escaneo completo."
		exit 1
		;;
	2 ) 
		FILE_LOG=$(date +%d-%m-%Y)_resultado
		echo "El resultado del escaneo se guardará en $RUTA_LOG_SCAN_FILE/$FILE_LOG"
		echo "El escaneo iniciará en 5 segundos..."
		for USER in `cat /etc/trueuserdomains | awk '{print $2}'`
		do
        	if [ "$USER" != "patovs" ]
        	then
                echo -e "========================================================= $USER =============================================================\n" >> $RUTA_LOG_SCAN_FILE/$FILE_LOG
                egrep -n -r -I --exclude="sym" '(\\x[a-z]|\\x[0-9]|<?php if\(isset\(|eval\(base64_decode\(gzuncompress|gzuncompress|base64_decode|;eval\()|GIF89aG|b374k' /home/$USER/public_html --include=*.php | awk -F":" '{print $1":"$2":\t"$3}' | egrep '(:1:)' >> $RUTA_LOG_SCAN_FILE/$FILE_LOG
        	fi
		done
		echo "Escaneo terminado."
		exit 1
		;;
	3 )
		FILE_LOG=$(date +%d-%m-%Y)_resultado
		echo "El resultado del escaneo se guardará en $RUTA_LOG_SCAN_FILE/$FILE_LOG"
		echo "El escaneo iniciará en 5 segundos..."
		for USER in `cat /etc/trueuserdomains | awk '{print $2}'`
		do
        	if [ "$USER" != "patovs" ]
        	then
                echo -e "========================================================= $USER =============================================================\n" >> $RUTA_LOG_SCAN_FILE/$FILE_LOG
                egrep -n -r -I --exclude="root" '(\\x[a-z]|\\x[0-9]|<?php if\(isset\(|eval\(base64_decode\(gzuncompress|gzuncompress|base64_decode|;eval\()|GIF89aG|b374k' /home/$USER/public_html --include=*.php | awk -F":" '{print $1":"$2":\t"$3}' >> $RUTA_LOG_SCAN_FILE/$FILE_LOG
        	fi
		done
		echo "Escaneo terminado."
		exit 1
		;;
esac


