#!/bin/bash

echo "Ingrese el log a escanear : "
echo "(Debe ingresar la ruta completa del archivo)"

read FILE

for line in `cat $FILE`
do
	CARS=$(echo $line | awk -F: '{ print $1 }')
	NUMBER_LINE=$(echo $line | awk -F: '{ print $2 }')
	TARGET=$(echo $line | awk -F: '{ print $3 }')
	if [ $CARS -gt 9000 ]
	then
		echo "Procesando"
		CARSd=$CARS"d"
		sed -i "$CARSd" $TARGET
	fi
	

done
echo "nada que hacer"
