#!/bin/bash

echo "Ingrese el log a escanear : "
echo "(Debe ingresar la ruta completa del archivo)"

read FILE

for line in `cat $FILE`
do
	CARS=$(echo $line | awk -F: '{ print $1 }')
	NUMBER_LINE=$(echo $line | awk -F: '{ print $2 }')
	TARGET=$(echo $line | awk -F: '{ print $3 }')

	sed -i '$(echo $CARS)d' $TARGET

done
