#!/bin/bash

REPORTE_LOG=/root/apps/codes/log-scan/reporte_limpiar_$(date +%d%m%Y)
echo "Ingrese la ruta del log a ordenar"
read LOG

cat $LOG | egrep -v '^==' | sed '/^$/d' | awk -F: '{ print length($3)":"$2":"$1 }' | sort -rn > $REPORTE_LOG

echo "Reporte generado: $REPORTE_LOG"
echo "Programa terminado"
