#!/bin/bash

####### Funcion pausa ######
function pause(){
	read -p "$*"
}

function progressBar(){
	SPEED=0.1
	DEL="\\x08\\x08\\x08\\x08\\x08\\x08\\x08\\x08"
	PID=$1
	while [ -d /proc/$PID ];do
		echo -en "|-------" && sleep $SPEED && echo -en $DEL
    	echo -en "-/------" && sleep $SPEED && echo -en $DEL
	    echo -en "--\\-----" && sleep $SPEED && echo -en $DEL
    	echo -en "---|----" && sleep $SPEED && echo -en $DEL
	    echo -en "----/---" && sleep $SPEED && echo -en $DEL
    	echo -en "-----\\--" && sleep $SPEED && echo -en $DEL
	    echo -en "------|-" && sleep $SPEED && echo -en $DEL
    	echo -en "-------*" && sleep $SPEED && echo -en $DEL
	    echo -en "------|-" && sleep $SPEED && echo -en $DEL
    	echo -en "-----\\--" && sleep $SPEED && echo -en $DEL
	    echo -en "----/---" && sleep $SPEED && echo -en $DEL
    	echo -en "---|----" && sleep $SPEED && echo -en $DEL
	    echo -en "--\\-----" && sleep $SPEED && echo -en $DEL
    	echo -en "-/------" && sleep $SPEED && echo -en $DEL
	done
	echo -en $DEL"        "$DEL
	exit 0
}

#### Menu inicial #####
echo -e "
The script run a system scan to detect infections carried PHP\n
the types of detections current version performed are:\n
PASSTHRU\n
SHELL_EXEC\n
SYSTEM\n
PHPINFO\n
BASE64_DECODE\n
EDOCED_46ESAB\n
CHMOD\n
MKDIR\n
and others\n
"
pause 'Press [Enter] key to continue... Crtl+c to exit'

echo "To start choose an option"
echo ""
echo " 1 - cPanel hosting server"
echo " 2 - Personal folder"
echo " 3 - clean based on report generated"
echo "Choose an option : "
read OPCION

case $OPCION in

	1 ) 
		echo "Generating report..."
		RUTA_LOG_CPANEL_OPTION=~/report_phpcleaner_cpanel_$(date +%d%m%Y)
		#### Generar Logs solamente ####
		#### Opcion para escanear en caso de cpanel #####
		for USER in `cat /etc/trueuserdomains | awk '{ print $2 }'`
		do
			echo -e "===== $USER =====\n" >> $RUTA_LOG_CPANEL_OPTION
			egrep -n -r -I '(\\x[a-z]|\\x[0-9]|<?php if\(isset\(|eval\(base64_decode\(gzuncompress|gzuncompress|base64_decode|;eval\()|GIF89aG|b374k' /home/$USER/public_html --include=*.php | awk -F":" '{ print $1":"$2":"$3 }' >> $RUTA_LOG_CPANEL_OPTION
		progressBar
		done
		
		echo "Finish!"
		exit 1
		;;
	2 ) 
		echo "Enter the path to scan"
		echo "Example: /home/usuario/data/code_php_folder"
		read PATH
		PERSONAL_FOLDER_LOG_FILE=~/report_personal_folder_$(date +%d%m%Y)
		egrep -n -r -I '(\\x[a-z]|\\x[0-9]|<?php if\(isset\(|eval\(base64_decode\(gzuncompress|gzuncompress|base64_decode|;eval\()|GIF89aG|b374k' $PATH --include=*.php | awk -F":" '{ print $1":"$2":"$3 }' > $PERSONAL_FOLDER_LOG_FILE
		echo "Generating report..."
		progressBar
		exit 1
		;;		
	3 ) 
		echo "Enter the report log name to clean the files on"
		echo "Example: /full_path/to/log_file/report_personal_folder_DATE"

		##### Opcion para eliminar los archivos infectados del logfile generado ####
		for line in `cat $PERSONAL_FOLDER_LOG_FILE | grep -v '^==' | sed '/^$/d'`
		do
			CARS=$(echo $line | awk -F: '{ print $1 }')
			NUMBER_LINE=$(echo $line | awk -F: '{ print $2 }')
			TARGET=$(echo $line | awk -F: '{ print $3 }')

			echo "sed -i '$(echo $CARS)d' $TARGET"

		done
		exit 1
		;;
esac
